# -*- coding: utf-8 -*-

import os


# POSTGRESQL CONFIGURATION

POSTGRES_DB = 'trackdechets'

POSTGRES_HOST = os.environ['POSTGRES_HOST']

POSTGRES_USER = os.environ['POSTGRES_USER']

POSTGRES_PWD = os.environ['POSTGRES_PWD']

POSTGRES_PORT = os.environ['POSTGRES_PORT']

# VHU CONFIGURATION

SIV_CENTRES_VHU_FILE_PATH = './data/VHU/Centres_VHU_20190517.pdf'